### PR TITLE
swagger: add activeMs

### PR DESCRIPTION
**Pull request by dsharrison**
This is the documentation update for https://github.com/samsara-dev/backend/pull/10589 and will be merged after that change lands.

### CODE REVIEW

**Comment by btuan** [comment]
Looks reasonable to me. Just for sanity-check, can you run the changed file through a swagger linter?
Maybe something like this?

https://editor.swagger.io/

**Comment by silverspace** [comment]
This looks fine to me. A higher level question: Do we want to expose sub-minute level precision to external customers for HOS data?

**Comment by silverspace** [comment]
I'm not sure about the data inaccuracies, that's certainly a possibility. I think the HOS app displays data with a granularity of a minute, so my question was whether we want to mirror the same precision in our APIs. 

In any case, I'm fairly certain we have precedent of using millisecond timestamps in our HOS APIs, so this was more of a follow-up question for Compliance about HOS API design.

**Comment by silverspace** [comment]
Should we merge this PR?

**Pull request merged**
